### ISSUE TITLE
Home page is completely empty

### ISSUE THREAD

**Issue by frogcrush** [CSSS/csss-site#189]
Hi from TRU!

You guys have a completely empty home page:
![image](https://user-images.githubusercontent.com/6116333/93527287-7c071d00-f8ed-11ea-88f7-a261b7b7d920.png)

**Comment by modernNeo** [comment]
@frogcrush I am aware, it was unfortunately necessary. will be providing a temp fix by end of week.

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/pull/190
